### ISSUE TITLE
Generating a blk-file not containing the interpreter

### ISSUE THREAD

**Issue by awest-swe** [howerj/forth-cpu#2]
Is there a way to generate blk-file only containing instructions for a very small program:
`1 $4006 !`
I've been experimenting a bit with embed (from the embed repo) but have not yet figured out if it is possible or not.
Thank you for sharing this project!

**Comment by howerj** [comment]
Yes it is possible! But I am not clear what you want to do. Are you intending to produce an image that works with the embed project, or with this Forth CPU? Presumably you want to set the timer (at location $4006) peripheral, and see this in the (H2 GUI) simulator? This project uses a version of the embed project (on the h2 branch) for cross compilation, but the embed VM itself does not have a timer peripheral.

I'll give you more detailed instructions tomorrow after work (it's getting late here).

**Comment by awest-swe** [comment]
It's for an embedded project! I've squeezed parts of the CPU into an ICE40 device _(ICE40HX1K-BLINK-EVN board)_ and would like to create a blinky applikation. The memory location $4006 is mapped to some I/O pins.
I not too familiar with Forth but generating a small test application seems doable.

**Comment by howerj** [comment]
I've pushed changes on a branch (called 'minimal'), there is an example program that contains just the meta-compiler (cross-compiler) and a small test program available in 't/minimal.fth'. Copy this over the top of the 'embed.fth' and build as usual. You should be able to use this for your development purposes. 

On line 274, where it says 'Start of Image', this is where the assembly of the target image actually begins. 

It sets all of the interrupt vectors to zero (all of the "0 t," statements). The first location is overwritten later on with a jump to our starting function.

I have also defined a few words which you might find useful (although you should not use them directly), they are:

     h: doVar   r> ;
     h: doConst r> @ ;

These are used by the meta-compiler when constants and variables (by using 'tconstant' and 'tvariable') are defined. If you try to make constants or variables before these two words are defined, then the meta-compiler will complain and fail.

You should define all words with 'h:' instead of ':', as you don't need the interpreter, you don't need to put the word header into the target image.

If you are not using interrupts, you can delete all of the "0 t," statements apart from the first one.

You need to bear in mind that writing a program for the meta-compiler is not like writing code for a normal Forth, it looks roughly the same, but it isn't!

Let me how you get on, or if you need any more instruction.

Thanks,
Richard

**Comment by howerj** [comment]
Did this help? I'd like to close this.

**Comment by awest-swe** [comment]
Yes, you can close this. Thanks for the great support, I've enjoyed the happiness of a green little light.
Think I understand what you mean about the meta-compiler, it provides a lot of flexibility. Played around with the store command so it pops 2 from the data-stack, but I need to spend some more time with Forth to make something really useful.
If you are interested in the modifications I've made to the H2 I can push for you to review. Nothing fancy, just a little more control over size so it fits smaller devices. Separate sizes for data and return stack and the possibility to change address width.

**Comment by howerj** [comment]
That's great! You should push your changes even if they don't get merged.

Let me know if you need any more instruction about the meta-compiler, just open up a new issue or email me.
