### ISSUE TITLE
Copy Documentation

### ISSUE THREAD

**Issue by PythonLinks** [howerj/forth-cpu#5]
So I have decided to use forth-cpu/embed.c  and forth-cpu/embed.fth as my forth interpreter.   They include a model of a stack cpu.  Most other forths are optimized for register machines.  So yours is closer to the hardware.   Both of those files were updated 2 months ago, the files over on embed/embed were updated 16 months ago.  These are newer. 

But there is some good documentation in 
https://github.com/howerj/embed/blob/master/embed.fth

This issue is just a reminder to copy it over to this repository, or if someone is new to this project, 
to go and read it over there.

**Comment by howerj** [comment]
The documentation has not been copied over for a reason. The reason is that the meta-compiler toolchain has not been ported across to a H2-like CPU (the meta-compiler will never run on the actual H2 CPU, for one the H2 does not have enough memory). The documentation would have to be updated to reflect this and it cannot just be copied across.
