### ISSUE TITLE
Will H2 run on cheaper FPGAs?

### ISSUE THREAD

**Issue by lf94** [howerj/forth-cpu#9]
The current FPGA's price seems a little prohibitive to larger adoption. Is there an FPGA around the $100 mark that could run H2?

Thanks! And wicked awesome project :)

**Comment by howerj** [comment]
It should run on quite cheap FPGAs, the Nexys 3 is quite an old board with
an old FPGA, the state of the art has moved on even for lower end devices
in the (nearly?) 13 years since it was released.

The entire H2 system takes up a fraction of the resources on that old FPGA,
that's including everything else such as the PS/2, VGA/VT100, SPI, UART,
etcetera. The core itself is quite tiny. I think you would struggle to find
a device that it doesn't run on.

Unfortunately I do not have a recommendation, and want to get a cheap board
that I can do my development on, when I get the time

**Comment by lf94** [comment]
Let me know when you pick one :) Im one of the few who want to *use* Forth, not write or work on one. I built the My4th Light Forth CPU by Dennis K. and it was awesome playing 2048 on it. Driving H2 would be awesome too!
